# https://travis-ci.org/zdevito/ATen
language: python
python:
    - 2.7
    - 3.6

dist: trusty

before_install:
    - sudo apt-get install -qq valgrind

install:
    - travis_retry pip install pyyaml typing

script:
    - cd aten
    - mkdir build install
    - cd build
    - cmake .. -DUSE_CUDA=OFF -DCMAKE_INSTALL_PREFIX=../install
    - make install
    - ../tools/run_tests.sh .
    - cd ..
    - tools/test_install.sh $(pwd)/install $(pwd)

matrix:
    fast_finish: true
    include:
        env: LINT_CHECK
        python: "2.7"
        install: pip install flake8-mypy
        script: flake8
