# binary linux build defaults
##############################################################################
binary_linux_build: &binary_linux_build
  resource_class: 2xlarge+
  steps:
  - run:
      <<: *binary_checkout
  - run:
      <<: *binary_populate_env
  - run:
      name: Install unbuffer and ts
      command: |
        set -ex
        source /env
        retry yum -q -y install epel-release
        retry yum -q -y install expect moreutils
  - run:
      name: Upgrade gcc version (based on env var)
      command: |
        set -ex
        source /env
        if [[ "$DESIRED_DEVTOOLSET" == 'devtoolset7' ]]; then
          source "/builder/upgrade_gcc_abi.sh"

          # Env variables are not persisted into the next step
          echo "export PATH=$PATH" > /env
          echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH" > /env
        else
          echo "Not upgrading gcc version"
        fi
  - run:
      name: Build
      no_output_timeout: "1h"
      command: |
        source "/pytorch/.circleci/scripts/binary_linux_build.sh"
  - persist_to_workspace:
      root: /
      paths: final_pkgs


# This should really just be another step of the binary_linux_build job above.
# This isn't possible right now b/c the build job uses the docker executor
# (otherwise they'd be really really slow) but this one uses the macine
# executor (b/c we have to run the docker with --runtime=nvidia and we can't do
# that on the docker executor)
binary_linux_test: &binary_linux_test
  machine:
    image: ubuntu-1604:201903-01
  steps:
  - run:
      <<: *setup_linux_system_environment
  - run:
      <<: *setup_ci_environment
  - attach_workspace:
      at: /home/circleci/project
  # This checkout is only needed to access
  # .circleci/scripts/binary_linux_test.sh, which can't be inlined because it
  # blows up the yaml size.
  - run:
      <<: *binary_checkout
  - run:
      <<: *binary_populate_env
  - run:
      name: Prepare test code
      no_output_timeout: "1h"
      command: |
        source "/home/circleci/project/pytorch/.circleci/scripts/binary_linux_test.sh"
  - run:
      <<: *binary_run_in_docker

binary_linux_upload: &binary_linux_upload
  machine:
    image: ubuntu-1604:201903-01
  steps:
  - run:
      <<: *setup_linux_system_environment
  - run:
      <<: *setup_ci_environment
  - attach_workspace:
      at: /home/circleci/project
  # This checkout is only needed to access
  # .circleci/scripts/binary_linux_upload.sh, which can't be inlined because it
  # blows up the yaml size.
  - run:
      <<: *binary_checkout
  - run:
      <<: *binary_populate_env
  - run:
      <<: *binary_install_miniconda
  - run:
      name: Upload
      no_output_timeout: "1h"
      command: |
        source "/home/circleci/project/pytorch/.circleci/scripts/binary_linux_upload.sh"
