
##############################################################################
# Macos binary build defaults
# The root of everything is /Users/distiller/pytorch-ci-env/workspace
##############################################################################
binary_mac_build: &binary_mac_build
  macos:
    xcode: "9.0"
  steps:
  - run:
      <<: *binary_checkout
  - run:
      <<: *binary_populate_env
  - run:
      <<: *macos_brew_update
  - run:
      <<: *binary_install_miniconda

  - run:
      name: Build
      no_output_timeout: "1h"
      command: |
        set -ex
        script="/Users/distiller/project/pytorch/.circleci/scripts/binary_macos_build.sh"
        cat "$script"
        source "$script"

  - run:
      name: Test
      no_output_timeout: "1h"
      command: |
        set -ex
        script="/Users/distiller/project/pytorch/.circleci/scripts/binary_macos_test.sh"
        cat "$script"
        source "$script"

  - persist_to_workspace:
      root: /Users/distiller/project
      paths: final_pkgs

binary_mac_upload: &binary_mac_upload
  macos:
    xcode: "9.0"
  steps:
  - run:
      <<: *binary_checkout
  - run:
      <<: *binary_populate_env
  - run:
      <<: *macos_brew_update
  - run:
      <<: *binary_install_miniconda
  - attach_workspace:
      at: /Users/distiller/project
  - run:
      name: Upload
      no_output_timeout: "10m"
      command: |
        script="/Users/distiller/project/pytorch/.circleci/scripts/binary_macos_test.sh"
        cat "$script"
        source "$script"
