
##############################################################################
# Macos build defaults
##############################################################################

caffe2_macos_build_defaults: &caffe2_macos_build_defaults
  macos:
    xcode: "9.0"
  steps:
    - checkout
    - run:
        <<: *macos_brew_update
    - run:
        name: Build
        no_output_timeout: "1h"
        command: |
          set -e

          export IN_CIRCLECI=1

          brew install cmake

          # Reinitialize submodules
          git submodule sync && git submodule update -q --init --recursive

          # Reinitialize path (see man page for path_helper(8))
          eval `/usr/libexec/path_helper -s`

          # Use Homebrew Python if configured to do so
          if [ "${PYTHON_INSTALLATION}" == "homebrew" ]; then
            export PATH=/usr/local/opt/python/libexec/bin:/usr/local/bin:$PATH
          fi

          pip -q install numpy

          # Install Anaconda if we need to
          if [ -n "${CAFFE2_USE_ANACONDA}" ]; then
            rm -rf ${TMPDIR}/anaconda
            curl -o ${TMPDIR}/conda.sh https://repo.continuum.io/miniconda/Miniconda${ANACONDA_VERSION}-latest-MacOSX-x86_64.sh
            chmod +x ${TMPDIR}/conda.sh
            /bin/bash ${TMPDIR}/conda.sh -b -p ${TMPDIR}/anaconda
            rm -f ${TMPDIR}/conda.sh
            export PATH="${TMPDIR}/anaconda/bin:${PATH}"
            source ${TMPDIR}/anaconda/bin/activate
          fi

          # Install sccache
          sudo curl https://s3.amazonaws.com/ossci-macos/sccache --output /usr/local/bin/sccache
          sudo chmod +x /usr/local/bin/sccache
          export SCCACHE_BUCKET=ossci-compiler-cache-circleci-v2

          # This IAM user allows write access to S3 bucket for sccache
          export AWS_ACCESS_KEY_ID=${CIRCLECI_AWS_ACCESS_KEY_FOR_SCCACHE_S3_BUCKET_V3}
          export AWS_SECRET_ACCESS_KEY=${CIRCLECI_AWS_SECRET_KEY_FOR_SCCACHE_S3_BUCKET_V3}

          export SCCACHE_BIN=${PWD}/sccache_bin
          mkdir -p ${SCCACHE_BIN}
          if which sccache > /dev/null; then
            printf "#!/bin/sh\nexec sccache $(which clang++) \$*" > "${SCCACHE_BIN}/clang++"
            chmod a+x "${SCCACHE_BIN}/clang++"

            printf "#!/bin/sh\nexec sccache $(which clang) \$*" > "${SCCACHE_BIN}/clang"
            chmod a+x "${SCCACHE_BIN}/clang"

            export PATH="${SCCACHE_BIN}:$PATH"
          fi

          # Build
          if [ "${BUILD_IOS:-0}" -eq 1 ]; then
            unbuffer scripts/build_ios.sh 2>&1 | ts
          elif [ -n "${CAFFE2_USE_ANACONDA}" ]; then
            # All conda build logic should be in scripts/build_anaconda.sh
            unbuffer scripts/build_anaconda.sh 2>&1 | ts
          else
            unbuffer scripts/build_local.sh 2>&1 | ts
          fi

          # Show sccache stats if it is running
          if which sccache > /dev/null; then
            sccache --show-stats
          fi


