# Nighlty build smoke tests defaults
# These are the second-round smoke tests. These make sure that the binaries are
# correct from a user perspective, testing that they exist from the cloud are
# are runnable. Note that the pytorch repo is never cloned into these jobs
##############################################################################
smoke_linux_test: &smoke_linux_test
  machine:
    image: ubuntu-1604:201903-01
  steps:
  - run:
      <<: *setup_linux_system_environment
  - run:
      <<: *setup_ci_environment
  - run:
      <<: *binary_populate_env
  - run:
      name: Test
      no_output_timeout: "1h"
      command: |
        set -ex
        cat >/home/circleci/project/ci_test_script.sh <<EOL
        # The following code will be executed inside Docker container
        set -ex
        git clone https://github.com/pytorch/builder.git /builder
        /builder/smoke_test.sh
        # The above code will be executed inside Docker container
        EOL
  - run:
      <<: *binary_run_in_docker

smoke_mac_test: &smoke_mac_test
  macos:
    xcode: "9.0"
  steps:
    - run:
        <<: *binary_populate_env
    - run:
        <<: *macos_brew_update
    - run:
        name: Build
        no_output_timeout: "1h"
        command: |
          set -ex
          source "/Users/distiller/project/env"
          git clone https://github.com/pytorch/builder.git
          unbuffer ./builder/smoke_test.sh | ts



