      #- binary_linux_libtorch_2.7m_cpu_test:
      #    requires:
      #      - binary_linux_libtorch_2.7m_cpu_build
      #- binary_linux_libtorch_2.7m_cu80_test:
      #    requires:
      #      - binary_linux_libtorch_2.7m_cu80_build
      #- binary_linux_libtorch_2.7m_cu90_test:
      #    requires:
      #      - binary_linux_libtorch_2.7m_cu90_build
      #- binary_linux_libtorch_2.7m_cu100_test:
      #    requires:
      #      - binary_linux_libtorch_2.7m_cu100_build

      # Nightly uploads
